---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: infra
  name: elasticsearch-master-config
  labels:
    app: elasticsearch
    role: master
data:
  elasticsearch.yml: |-
    cluster.name: ${CLUSTER_NAME}
    node.name: ${NODE_NAME}
    discovery.seed_hosts: ${NODE_LIST}
    cluster.initial_master_nodes: ${MASTER_NODES}
    network.host: 0.0.0.0
    node.roles: ["master"]
    indices.recovery.max_bytes_per_sec: 50mb
    indices.memory.index_buffer_size: 40%
    xpack.security.enabled: false
# thread_pool.search.max_queue_size: 10000
# thread_pool.search.target_response_time: 8s
# xpack.license.self_generated.type: trial
# xpack.security.http.ssl.enabled: true
# xpack.security.http.ssl.key: /home/ec2-user/elasticsearch-7.10.2/config/privateKey.key
# xpack.security.http.ssl.certificate: /home/ec2-user/elasticsearch-7.10.2/config/certificate.crt
# xpack.security.transport.ssl.enabled: true
# xpack.security.transport.ssl.verification_mode: none
# xpack.security.transport.ssl.certificate: /home/ec2-user/elasticsearch-7.10.2/config/certificate.crt
# xpack.security.transport.ssl.key: /home/ec2-user/elasticsearch-7.10.2/config/privateKey.key
# xpack.security.transport.ssl.client_authentication: optional
# xpack.security.http.ssl.verification_mode: none
# xpack.security.http.ssl.client_authentication: optional
---
