---
apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: elasticsearch-client
  labels:
    app: elasticsearch
    role: client
spec:
  selector:
    app: elasticsearch
    role: client
#  type: NodePort
  ports:
  - port: 9200
#    targetPort: 9200
#    nodePort: 31200
    name: client
  - port: 9300
    name: transport
---