---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: infra
  name: elasticsearch-data-config
  labels:
    app: elasticsearch
    role: data
data:
  elasticsearch.yml: |-
    cluster.name: ${CLUSTER_NAME}
    node.name: ${NODE_NAME}
    discovery.seed_hosts: ${NODE_LIST}
    cluster.initial_master_nodes: ${MASTER_NODES}
    network.host: 0.0.0.0
    node.roles: ["data"]
    xpack.security.enabled: false
    indices.recovery.max_bytes_per_sec: 50mb
    indices.memory.index_buffer_size: 40%
#    xpack.monitoring.collection.enabled: true
---